### ISSUE TITLE
Bubble's contents covered by timeline

### ISSUE THREAD

**Issue by diegonc** [christabor/css-progress-wizard#13]
Hello,

I'm not sure whether this use case has not been taken in account or if it is a bug. But when I added some content to the bubble's span it was covered by the timeline.

As illustrated in this CodePen [$], I managed to fix/workaround it by adding a negative `z-index` to the pseudo-elements that are used to render the timeline.

Is it the right way to do it? Are there better alternatives?

---

[$] There are two steps with some icons inside the bubbles. The first one has the fix and is correctly rendered. However, the second step show the timeline covers the icon.

http://codepen.io/diegonc/pen/yazNyV

**Comment by christabor** [comment]
Hi there, 

I'd say it's kind of split. I never intended for content to go inside the bubble `span` element, but this looks like a use-case I never considered either. If you look at the examples at http://christabor.github.io/css-progress-wizard/, there are icons, but they are shown below, rather than inside. I like the way yours looks though, and can imagine someone would want to do this.

I think the solution you have may be appropriate, if I add more and then simplify the css you have like so:

``` css
.my-timeline .progress-indicator .bubble:before, .my-timeline .progress-indicator .bubble:after {
  z-index: -1;
}
```

it works for all icons pretty well. I would consider adding this as a feature and updating the examples. If you'd like, feel free to make a pull request for it.
